const FETCH_PRODUCT_CATEGORIES = "FETCH_PRODUCT_CATEGORIES";
const PRODUCT_CATEGORIES_API = process.env.REACT_APP_API_URL + '/products/categories';

export {
    FETCH_PRODUCT_CATEGORIES,
    PRODUCT_CATEGORIES_API
}