const FETCH_PRODUCTS = "FETCH_PRODUCTS";
const FETCH_PRODUCT_DETAILS = "FETCH_PRODUCT_DETAILS";
const PRODUCTS_API = process.env.REACT_APP_API_URL + '/products';

export {
    FETCH_PRODUCTS,
    FETCH_PRODUCT_DETAILS,
    PRODUCTS_API
}